sudo: required
services:
  - docker

before_install:
  - docker build -t meltedspork/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true meltedspork/docker-react npm run test -- --coverage